/**
 * id : blog index
 * title : title of blog
 * filename : blog filename
 * img : blog img filename
 * tag : blog tag(max 3)
 * filter : filter tag */

export type recentPostDataType = {
    id: number;
    title: string;
    filename: string;
    imgLineOne: string;
    imgLineTwo: string;
    date: string;
    tag: string;
    tag2: string;
    tag3: string;
    filter: string;
};

export type recentPostsDataType = recentPostDataType[];

const recentPostsData: recentPostsDataType = [
    {
        id: 1,
        title: "타입스크립트를 많이 쓰는 이유",
        filename: "Typescript",
        date: "2021-11-17",
        imgLineOne: "Why",
        imgLineTwo: "typescript?",
        tag: "react",
        tag2: "ts",
        tag3: "",
        filter: "react",
    },
    {
        id: 2,
        title: "React Native - 네이티브 카메라 사용하기",
        filename: "Camera",
        date: "2021-11-26",
        imgLineOne: "React-Native",
        imgLineTwo: "Camera",
        tag: "react-native",
        tag2: "module",
        tag3: "camera",
        filter: "react",
    },
    {
        id: 3,
        title: "CORS와 해결방법",
        filename: "Cors",
        imgLineOne: "",
        imgLineTwo: "CORS",
        date: "2021-12-09",
        tag: "cors",
        tag2: "frontend",
        tag3: "backend",
        filter: "backend",
    },
    {
        id: 4,
        title: "Flask 튜토리얼",
        filename: "Flask",
        imgLineOne: "Python",
        imgLineTwo: "Flask",
        date: "2021-12-11",
        tag: "python",
        tag2: "flask",
        tag3: "backend",
        filter: "python",
    },
    {
        id: 5,
        title: "비선형구조 정리",
        filename: "NonLinear",
        imgLineOne: "",
        imgLineTwo: "Non-Linear",
        date: "2021-12-17",
        tag: "C",
        tag2: "tree",
        tag3: "graph",
        filter: "c",
    },
    {
        id: 6,
        title: "Window 터미널 꾸미기",
        filename: "Ohmyposh",
        imgLineOne: "Oh My",
        imgLineTwo: "Posh",
        date: "2021-12-18",
        tag: "terminal",
        tag2: "window",
        tag3: "",
        filter: "etc",
    },
    {
        id: 7,
        title: "Big-O 표기법과 수행",
        filename: "Algorithm",
        imgLineOne: "",
        imgLineTwo: "Big-O",
        date: "2021-12-20",
        tag: "Big O",
        tag2: "sort",
        tag3: "DP",
        filter: "c",
    },
    {
        id: 8,
        title: "개인 블로그를 개발한 이유",
        filename: "Blog",
        date: "2022-01-09",
        imgLineOne: "",
        imgLineTwo: "My Blog",
        tag: "blog",
        tag2: "gatsby",
        tag3: "ts",
        filter: "react",
    },
    {
        id: 9,
        title: "C++ 예외처리 매커니즘 - try, catch",
        filename: "Cpp-exception",
        date: "2022-03-02",
        imgLineOne: "C++",
        imgLineTwo: "Exception",
        tag: "cpp",
        tag2: "exception",
        tag3: "try, catch",
        filter: "cpp",
    },
    {
        id: 10,
        title: "힙 정렬에 대해 알아보자",
        filename: "Heapsort",
        date: "2022-03-21",
        imgLineOne: "",
        imgLineTwo: "Heap sort",
        tag: "cpp",
        tag2: "algorighm",
        tag3: "",
        filter: "cpp",
    },
    {
        id: 11,
        title: "Type-Alias 타입 앨리어스란?",
        filename: "Type-alias",
        date: "2022-04-30",
        imgLineOne: "",
        imgLineTwo: "Type-alias",
        tag: "ts",
        tag2: "type",
        tag3: "interface",
        filter: "ts",
    },
    {
        id: 12,
        title: "IoC: 제어의 역전",
        filename: "Ioc",
        date: "2022-05-25",
        imgLineOne: "",
        imgLineTwo: "IOC",
        tag: "spring",
        tag2: "",
        tag3: "",
        filter: "java",
    },
    {
        id: 13,
        title: "클린 아키텍처에 대해 알아보자",
        filename: "The-clean-architecture",
        date: "2022-05-30",
        imgLineOne: "Clean",
        imgLineTwo: "Architecture",
        tag: "architecture",
        tag2: "dependency",
        tag3: "",
        filter: "architecture",
    },
    {
        id: 14,
        title: "SQL 개발자 자격증 취득 후기",
        filename: "Sql-developer",
        date: "2022-06-20",
        imgLineOne: "",
        imgLineTwo: "SQLD",
        tag: "sql",
        tag2: "certification",
        tag3: "",
        filter: "sql",
    },
    {
        id: 15,
        title: "다익스트라 알고리즘 정리",
        filename: "Dijkstra",
        date: "2022-08-18",
        imgLineOne: "",
        imgLineTwo: "Dijkstra",
        tag: "algorithm",
        tag2: "cpp",
        tag3: "",
        filter: "cpp",
    },
    {
        id: 16,
        title: "플로이드 워셜 알고리즘 정리",
        filename: "Floyed-warshell",
        date: "2022-08-28",
        imgLineOne: "Floyed",
        imgLineTwo: "Warshell",
        tag: "algorithm",
        tag2: "cpp",
        tag3: "",
        filter: "cpp",
    },
    {
        id: 17,
        title: "KMP 알고리즘 정리",
        filename: "KMP",
        date: "2022-08-31",
        imgLineOne: "",
        imgLineTwo: "KMP",
        tag: "algorithm",
        tag2: "cpp",
        tag3: "",
        filter: "cpp",
    },
    {
        id: 18,
        title: "React에서 setInterval의 한계점",
        filename: "useInterval",
        date: "2022-12-15",
        imgLineOne: "React",
        imgLineTwo: "LifeCycle",
        tag: "react",
        tag2: "",
        tag3: "",
        filter: "react",
    },
    {
        id: 19,
        title: "Gatsby에서 UseSearchParam 커스텀 훅 만들기",
        filename: "UseSearchParam",
        date: "2022-12-26",
        imgLineOne: "",
        imgLineTwo: "Custom Hook",
        tag: "gatsby",
        tag2: "ts",
        tag3: "",
        filter: "gatsby",
    },
    {
        id: 20,
        title: "2022년 회고와 앞으로의 목표",
        filename: "Review2022",
        date: "2022-12-29",
        imgLineOne: "2022",
        imgLineTwo: "Review",
        tag: "",
        tag2: "",
        tag3: "",
        filter: "",
    },
    {
        id: 21,
        title: "Gradle을 kotiln dsl로 마이그레이션",
        filename: "Kts",
        date: "2023-04-04",
        imgLineOne: "kts",
        imgLineTwo: "migration",
        tag: "spring boot",
        tag2: "kotiln",
        tag3: "grandle",
        filter: "spring",
    },
    {
        id: 22,
        title: "CSRF(Cross-Site Request Forgery) 공격",
        filename: "Csrf",
        date: "2023-04-06",
        imgLineOne: "",
        imgLineTwo: "CSRF",
        tag: "csrf",
        tag2: "security",
        tag3: "spring",
        filter: "security",
    },
    {
        id: 23,
        title: "SQL injection 공격",
        filename: "Sql-Injection",
        date: "2023-04-20",
        imgLineOne: "SQL",
        imgLineTwo: "Injection",
        tag: "SQLi",
        tag2: "security",
        tag3: "",
        filter: "security",
    },
    {
        id: 24,
        title: "Spring에서 Multipart 다루기",
        filename: "Multipart",
        date: "2023-04-21",
        imgLineOne: "",
        imgLineTwo: "Multipart",
        tag: "spring",
        tag2: "file",
        tag3: "multipart",
        filter: "spring",
    },
    {
        id: 25,
        title: "자바에 나오는 모든 디자인 패턴 정리 - 1편",
        filename: "Pattern",
        date: "2023-04-25",
        imgLineOne: "Design",
        imgLineTwo: "Pattern",
        tag: "design-pattern",
        tag2: "java",
        tag3: "",
        filter: "java",
    },
    // {
    //     id: 26,
    //     title: "Novel Cloud 프로젝트 진행 회고",
    //     filename: "NovelCloud",
    //     date: "2023-06-09",
    //     imgLineOne: "Novel",
    //     imgLineTwo: "Cloud",
    //     tag: "spring",
    //     tag2: "java",
    //     tag3: "",
    //     filter: "java",
    // },
    {
        id: 26,
        title: "영속성 컨텍스트 - 엔티티 생명주기",
        filename: "PersistenceContext",
        date: "2023-06-19",
        imgLineOne: "Persistence",
        imgLineTwo: "Context",
        tag: "spring",
        tag2: "jpa",
        tag3: "hibernate",
        filter: "java",
    },
    {
        id: 27,
        title: "@ModelAttribute 사용법",
        filename: "ModelAttribute",
        date: "2023-06-20",
        imgLineOne: "Model",
        imgLineTwo: "Attribute",
        tag: "spring",
        tag2: "annotation",
        tag3: "",
        filter: "java",
    },
    {
        id: 28,
        title: "EC2 서버에서 온프레미스 Window 서버로 마이그레이션을 진행한 과정",
        filename: "Migration-ec2-to-window",
        date: "2023-07-08",
        imgLineOne: "",
        imgLineTwo: "Migration",
        tag: "migration",
        tag2: "nginx",
        tag3: "spring",
        filter: "server",
    },
];

export default recentPostsData;
